# Generated by Django 3.1 on 2020-08-13 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuboid',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 5, 16, 46, 84560)),
        ),
        migrations.AlterField(
            model_name='filterarea',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 5, 16, 46, 89121)),
        ),
        migrations.AlterField(
            model_name='filterheight',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 5, 16, 46, 88117)),
        ),
        migrations.AlterField(
            model_name='filterlength',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 5, 16, 46, 86088)),
        ),
        migrations.AlterField(
            model_name='filtervolume',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 5, 16, 46, 90086)),
        ),
        migrations.AlterField(
            model_name='filtervolume',
            name='volume',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='filterwidth',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 5, 16, 46, 86973)),
        ),
    ]
