# Generated by Django 3.1 on 2020-08-13 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_api', '0003_auto_20200813_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuboid',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 21, 58, 214057)),
        ),
        migrations.AlterField(
            model_name='filterarea',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 21, 58, 212908)),
        ),
        migrations.AlterField(
            model_name='filterheight',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 21, 58, 212458)),
        ),
        migrations.AlterField(
            model_name='filterlength',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 21, 58, 211542)),
        ),
        migrations.AlterField(
            model_name='filtervolume',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 21, 58, 213334)),
        ),
        migrations.AlterField(
            model_name='filterwidth',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 21, 58, 212018)),
        ),
    ]
