# Generated by Django 3.1 on 2020-08-13 13:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_api', '0004_auto_20200813_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuboid',
            name='area',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='crud_api.filterarea'),
        ),
        migrations.AlterField(
            model_name='cuboid',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 28, 2, 646133)),
        ),
        migrations.AlterField(
            model_name='cuboid',
            name='height',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='crud_api.filterheight'),
        ),
        migrations.AlterField(
            model_name='cuboid',
            name='volume',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='crud_api.filtervolume'),
        ),
        migrations.AlterField(
            model_name='cuboid',
            name='width',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='crud_api.filterwidth'),
        ),
        migrations.AlterField(
            model_name='filterarea',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 28, 2, 648445)),
        ),
        migrations.AlterField(
            model_name='filterheight',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 28, 2, 647984)),
        ),
        migrations.AlterField(
            model_name='filterlength',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 28, 2, 646958)),
        ),
        migrations.AlterField(
            model_name='filtervolume',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 28, 2, 648899)),
        ),
        migrations.AlterField(
            model_name='filterwidth',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 28, 2, 647416)),
        ),
    ]
