# Generated by Django 3.1 on 2020-08-13 13:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crud_api', '0006_auto_20200813_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuboid',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cuboid',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 30, 20, 698664)),
        ),
        migrations.AlterField(
            model_name='filterarea',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 30, 20, 701049)),
        ),
        migrations.AlterField(
            model_name='filterheight',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 30, 20, 700540)),
        ),
        migrations.AlterField(
            model_name='filterlength',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 30, 20, 699496)),
        ),
        migrations.AlterField(
            model_name='filtervolume',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 30, 20, 701502)),
        ),
        migrations.AlterField(
            model_name='filterwidth',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 30, 20, 699961)),
        ),
    ]
